#
# Module manifest for module 'RunAsUser'
#
# Generated by: Kelvin Tegelaar - Kelvin@limenetworks.nl
#
# Generated on: 19/05/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = '.\RunAsUser.psm1'

    # Version number of this module.
    ModuleVersion     = '2.4.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '69c4dd7a-366a-42ec-907a-691d924b4e8b'

    # Author of this module
    Author            = 'Tim Brigham'

    # Company or vendor of this module
    CompanyName       = 'Tim Brigham'

    # Copyright statement for this module
    Copyright         = '(c) 2020 Kelvin Tegelaar - Kelvin@CyberDrain.com All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'This module allows you to execute scripts under the current user while running as SYSTEM using impersonation.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Invoke-AsCurrentUser'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('RMM', 'Invoke-AsCurrentUser')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/timbrigham-oc/RunAsUser/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/timbrigham-oc/RunAsUser'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'Branched at version 2.4.0 of the original RunAsUser module by Kelvin Tegelaar. This version is maintained by Tim Brigham.'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI       = 'https://github.com/timbrigham-oc/RunAsUser'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

